// DHAKA DISTRICT

export const dhakaCityArea = [
  { id: 1, name: 'Abdullahpur' },
  { id: 2, name: 'Agargaon' },
  { id: 3, name: 'Badda' },
  { id: 4, name: 'Banasree' },
  { id: 5, name: 'Banani' },
  { id: 6, name: 'Baridhara' },
  { id: 7, name: 'Bashundhara' },
  { id: 8, name: 'Bawnia' },
  { id: 9, name: 'Beraid' },
  { id: 10, name: 'Cantonment area' },
  { id: 11, name: 'Dakshinkhan' },
  { id: 12, name: 'Dania' },
  { id: 13, name: 'Demra' },
  { id: 14, name: 'Dhanmondi' },
  { id: 15, name: 'Farmgate' },
  { id: 16, name: 'Gabtali' },
  { id: 17, name: 'Gulshan' },
  { id: 18, name: 'Hazaribagh' },
  { id: 19, name: 'Islampur' },
  { id: 20, name: 'Jurain' },
  { id: 21, name: 'Kafrul' },
  { id: 22, name: 'Kamalapur' },
  { id: 23, name: 'Kamrangirchar' },
  { id: 24, name: 'Kazipara' },
  { id: 25, name: 'Khilgaon' },
  { id: 26, name: 'Khilkhet' },
  { id: 27, name: 'Kotwali' },
  { id: 28, name: 'Lalbagh' },
  { id: 29, name: 'Matuail' },
  { id: 30, name: 'Mirpur' },
  { id: 31, name: 'Mohakhali' },
  { id: 32, name: 'Mohammadpur' },
  { id: 33, name: 'Motijheel' },
  { id: 34, name: 'Niketan, Gulshan' },
  { id: 35, name: 'Nimtoli' },
  { id: 36, name: 'Pallabi' },
  { id: 37, name: 'Paltan' },
  { id: 38, name: 'Paribagh' },
  { id: 39, name: 'Ramna' },
  { id: 40, name: 'Rampura' },
  { id: 41, name: 'Sadarghat' },
  { id: 42, name: 'Satarkul' },
  { id: 43, name: 'Segunbagicha' },
  { id: 44, name: 'Sher-e-Bangla Nagar' },
  { id: 45, name: 'Shahbagh' },
  { id: 46, name: 'Shyampur' },
  { id: 47, name: 'Sutrapur' },
  { id: 48, name: 'Tejgaon' },
  { id: 49, name: 'Uttara' },
  { id: 50, name: 'Uttarkhan' },
  { id: 51, name: 'Vatara' },
  { id: 52, name: 'Wari' },
  { id: 53, name: 'Sadarghat' },
];


const savar = [
  { id: 1, name: "Ashulia" },
  { id: 2, name: "Birulia" },
  { id: 3, name: "Savar" },
];

const keraniganj = [
  { id: 1, name: "Hasnabad" },
  { id: 2, name: "Jinjira" },
  { id: 3, name: "Tegharia" },
  { id: 4, name: "Jhilmil" },
];
